import 'package:stamp_camera/src/core/model/stamp_edit_frame_shape.dart';
import 'package:stamp_camera/src/locale/locale_key.dart';
import 'package:stamp_camera/src/ui/creative/interactor/template_specs/creative_template_spec.dart';
import 'package:stamp_camera/src/utils/app_assets.dart';

const CreativeTemplateSpec templateNightStampCollageV2Spec =
    CreativeTemplateSpec(
      id: 'template_night_stamp_collage_v2',
      nameLocaleKey: LocaleKey.stampverseCreativeTemplateNightStampCollage,
      sourceWidth: 736,
      sourceHeight: 1041,
      showcaseImageAssetPath: AppAssets.creativeTemplateShowcaseTemplate2Png,
      editorBackgroundAssetPath:
          AppAssets.creativeTemplateBackgroundTemplate2Png,
      editorCanvasColorHex: '#000000',
      slotRects: <CreativeTemplateSlotSpec>[
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_1',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 27,
          topPx: 34,
          rightPx: 220,
          bottomPx: 288,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_2',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 232,
          topPx: 33,
          rightPx: 692,
          bottomPx: 288,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_3',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 26,
          topPx: 302,
          rightPx: 177,
          bottomPx: 596,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_4',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 191,
          topPx: 302,
          rightPx: 344,
          bottomPx: 495,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_5',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 354,
          topPx: 302,
          rightPx: 507,
          bottomPx: 495,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_6',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 520,
          topPx: 302,
          rightPx: 692,
          bottomPx: 496,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_7',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 189,
          topPx: 506,
          rightPx: 507,
          bottomPx: 720,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_8',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 518,
          topPx: 508,
          rightPx: 692,
          bottomPx: 723,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_9',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 26,
          topPx: 609,
          rightPx: 179,
          bottomPx: 846,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_10',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 24,
          topPx: 856,
          rightPx: 175,
          bottomPx: 1001,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_11',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 189,
          topPx: 732,
          rightPx: 383,
          bottomPx: 999,
          frameShape: StampEditFrameShape.stampClassic,
        ),
        CreativeTemplateSlotRect.fromSourcePixels(
          id: 'slot_12',
          sourceWidth: 736,
          sourceHeight: 1041,
          leftPx: 394,
          topPx: 733,
          rightPx: 692,
          bottomPx: 999,
          frameShape: StampEditFrameShape.stampClassic,
        ),
      ],
    );
